### ISSUE TITLE
Fix mixer add leaves in client

### ISSUE THREAD

**Issue by drewstone** [edgeware-builders/anon#60]
When we generate a proof against a merkle tree for some root, we need to ensure that the respective merkle tree that we reconstruct stops at that root. Right now it is possible for the root we want to prove against and the current state of the merkle tree on chain to diverge, and so fail to generate proofs.

This first requires adding a target root to the function and incrementally building the tree UNTIL we reach that root, this way we then have the state of the tree we can generate a proof path from.

**Comment by filiplazovic** [comment]
I get what you mean, but I think this is not the case. VSMT saves all the intermediate states, so you can make a proof for any root hash that existed in the past. Need to check this twice, so worth testing out

**Comment by drewstone** [comment]
Ok I think you are probably right. I'll dive more deeply and try to see how long this cache lasts for over old states.

**Comment by drewstone** [comment]
I think we'll still want to have a stop-gap nonetheless no? It's an optimisation that saves the client some time/memory in any case.

**Comment by filiplazovic** [comment]
Yeah, I guess it could be used as an optimization method
